default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: codeboxx.cq6zrczewpu2.us-east-1.rds.amazonaws.com
  username: codeboxx
  password: Codeboxx1!
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: LoicRico

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['USERSTEST_DATABASE_PASSWORD'] %>