default: &default
  adapter: postgresql
  encoding: unicode
  username: codeboxx
  password: Codeboxx1!
  host: codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: LoicRico_dwh

test:
  <<: *default
  database: dwh_test

production:
  <<: *default
  database: dwh_production
  username: dwh
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>